project:
  type: website
  output-dir: rendered
  resources: 
    - _assets/*
    - CNAME

website:
  title: "roughdata"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog/index.qmd
        text: Blog
      - href: about.qmd
        text: About
  search:
    location: navbar
    type: textbox



format:
  html:
    theme:
      light:
        - default
        - brite.scss
      dark:
        - default
        - brite.scss
    respect-user-color-scheme: true
    toc: true

execute:
  freeze: auto

